### ISSUE TITLE
404 on npm.js

### ISSUE THREAD

**Issue by MuraraAllan** [floatdrop/read-all-stream#12]
Hey i just found out your package is not on npm.js anymore. Thanks \o

**Comment by micurley** [comment]
same here

**Comment by micurley** [comment]
you're back :)

**Comment by BrodaNoel** [comment]
Missing file: https://registry.npmjs.org/read-all-stream/-/read-all-stream-3.1.0.tgz

**Comment by MuraraAllan** [comment]
Package back on track, thanks @floatdrop !

**Comment by floatdrop** [comment]
@MuraraAllan kudos to npm team for fixing this quickly – https://status.npmjs.org/incidents/41zfb8qpvrdj
