### ISSUE TITLE
Streams2

### ISSUE THREAD

**Issue by sindresorhus** [floatdrop/read-all-stream#2]
You're using push streams. Not sure if this would benefit from Streams2 pull streams, but why not.

http://strongloop.com/strongblog/whats-new-io-js-beta-streams3/

-

Can you also bump this to 1.0.0 afterwards?

**Comment by floatdrop** [comment]
Since main usage is to get all data into internal buffer - there will be no difference (you can not call pause on response object), but will look at this article closely tomorrow.

**Comment by sindresorhus** [comment]
Yeah, I figured. But still nice to use the newest API, even without any immediate benefit.

**Comment by floatdrop** [comment]
Done - https://github.com/floatdrop/read-all-stream/releases/tag/v1.0.0

**Comment by floatdrop** [comment]
Seems like I don't understand how Streams2 work after all - we have bug in production, that causes data loss (got returns empty string).

**Comment by sindresorhus** [comment]
Weird, it looked ok to me.
